name: precompile-aarch64-linux-gnu

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  aarch64-linux-gnu:
    name: aarch64-linux-gnu
    runs-on: ubuntu-20.04
    env:
      BIGQUERY_VERSION: "2.22.0"
      TRIPLET: "aarch64-linux-gnu"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake git curl \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Compile everything
        run: |
          make NPROC=2

      - name: Create tarball
        run: |
          export FILENAME="bigquery-${{ env.BIGQUERY_VERSION }}-${{ env.TRIPLET }}"
          tar -czf "${FILENAME}.tar.gz" -C install .
          sha256sum "${FILENAME}.tar.gz" | tee "${FILENAME}.tar.gz.sha256"
      
      - uses: softprops/action-gh-release@v2
        with:
          name: "v${{ env.BIGQUERY_VERSION }}"
          tag_name: "v${{ env.BIGQUERY_VERSION }}"
          files: |
            bigquery-*.tar.gz
            bigquery-*.tar.gz.sha256
