name: precompile-windows

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-2019

    name: x86_64-windows-msvc

    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install dependencies
        run: |
          choco install -y nasm
          choco install -y ninja
          choco install -y cmake
      
      - name: Compile everything
        run: |
          nmake /F Makefile.win

      - name: Create tarball
        shell: bash
        run: |
          export BIGQUERY_VERSION=${GITHUB_REF##*/v}
          export TRIPLET="x86_64-windows-msvc"
          export ROOTDIR="$(pwd)"
          cd install
          tar -czf "${ROOTDIR}/bigquery-${BIGQUERY_VERSION}-${TRIPLET}.tar.gz" .
          cd "${ROOTDIR}"
          shasum -a 256 "bigquery-${BIGQUERY_VERSION}-${TRIPLET}.tar.gz" | tee "bigquery-${BIGQUERY_VERSION}-${TRIPLET}.tar.gz.sha256"

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bigquery-*.tar.gz
            bigquery-*.tar.gz.sha256

