name: precompile-macos

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  macos:
    name: ${{ matrix.job.arch }}-apple-darwin
    runs-on: ${{ matrix.job.runner }}
    env:
      BIGQUERY_VERSION: "2.22.0"
    strategy:
      matrix:
        job:
          - { arch: x86_64, runner: macos-12 }
          - { arch: aarch64, runner: macos-14 }
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install autoconf automake libtool shtool openssl

      - name: Compile everything
        run: |          
          make NPROC=2

      - name: Create tarball
        run: |
          export TRIPLET="${{ matrix.job.arch }}-apple-darwin"
          export FILENAME="bigquery-${{ env.BIGQUERY_VERSION }}-${TRIPLET}"
          tar -czf "${FILENAME}.tar.gz" -C install .
          shasum -a 256 "${FILENAME}.tar.gz" | tee "${FILENAME}.tar.gz.sha256"

      - uses: softprops/action-gh-release@v2
        with:
          name: "v${{ env.BIGQUERY_VERSION }}"
          tag_name: "v${{ env.BIGQUERY_VERSION }}"
          files: |
            bigquery-*.tar.gz
            bigquery-*.tar.gz.sha256

      - name: Cleanup
        if: always()
        run: |
          make clean
          sudo rm -rf bigquery-*.tar.gz bigquery-*.tar.gz.sha256
