name: precompile-x86_64-linux-gnu

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  x86_64-linux-gnu:
    name: x86_64-linux-gnu
    runs-on: ubuntu-latest
    env:
      BIGQUERY_VERSION: "2.22.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull docker image
        run: |
          sudo docker pull -platform=linux/amd64 ubuntu:20.04

      - name: Precompile
        run: |
          cp .github/script-to-build-gnu.sh ./
          cp .github/do-build.sh ./

          bash ./script-to-build-gnu.sh "${{ env.BIGQUERY_VERSION }}" "x86_64"

      - uses: softprops/action-gh-release@v2
        with:
          name: "v${{ env.BIGQUERY_VERSION }}"
          tag_name: "v${{ env.BIGQUERY_VERSION }}"
          files: |
            bigquery-*.tar.gz
            bigquery-*.tar.gz.sha256

      - name: Cleanup
        if: always()
        run: |
          sudo rm -rf bigquery-*.tar.gz bigquery-*.tar.gz.sha256
          sudo rm -rf script-to-build-gnu.sh do-build.sh
